[workspace]

members = [
    "web-markdown",
    "dioxus-markdown",
    "leptos-markdown",
    "yew-markdown",
    "dioxus-markdown/examples/*",
    "leptos-markdown/examples/*",
    "yew-markdown/examples/*",
]
resolver = "2"
